name: Poetry App CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "2.1.3"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run black (check only)
        run: poetry run black . --check

      - name: Run ruff
        run: poetry run ruff .

  deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker auth
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: pieces-justificatives-461014

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t europe-west1-docker.pkg.dev/pieces-justificatives-461014/poetry-app/poetry-app --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy YOUR_SERVICE_NAME \
            --image europe-west1-docker.pkg.dev/pieces-justificatives-461014/poetry-app/poetry-app \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated